CREATE TABLE catchmi.joblist (
	comp VARCHAR(30) NULL DEFAULT NULL,
	gbn VARCHAR(10) NULL DEFAULT NULL,
	s_url VARCHAR(500) NOT NULL,
	s_status VARCHAR(10) NULL DEFAULT 0,
	startdt DATETIME NULL DEFAULT NULL,
	enddt DATETIME NULL DEFAULT NULL,
	rrsidno VARCHAR(30) NULL DEFAULT 'SYSTEM',
	rrt DATETIME NULL DEFAULT NULL
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
