CREATE TABLE `stk_com_mt` (
	`CO_NM` VARCHAR(100) NOT NULL,
	`CO_CD` VARCHAR(40) NOT NULL,
	`ST_DT` VARCHAR(8) NULL DEFAULT NULL,
	`EN_DT` VARCHAR(8) NULL DEFAULT NULL,
	`use_yn` VARCHAR(4) NOT NULL DEFAULT 'Y',
	`cat01` VARCHAR(10) NULL DEFAULT NULL,
	`cat02` VARCHAR(10) NULL DEFAULT NULL,
	`cat03` VARCHAR(10) NULL DEFAULT NULL,
	`cat04` VARCHAR(10) NULL DEFAULT NULL,
	`cat05` VARCHAR(10) NULL DEFAULT NULL,
	`rrsidno` VARCHAR(40) NOT NULL DEFAULT 'SYSTEM',
	`rrt` DATE NULL DEFAULT NULL,
	`modidno` VARCHAR(40) NULL DEFAULT NULL,
	`modrrt` DATE NULL DEFAULT NULL
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
