CREATE TABLE `stk_prc_mt` (
	`CO_CD` VARCHAR(40) NOT NULL,
	`ES_DT` VARCHAR(8) NOT NULL,
	`ES_TIME` VARCHAR(6) NULL DEFAULT NULL,
	`ES_ENVL` INT(11) NOT NULL,
	`ES_GAP` INT(11) NULL DEFAULT NULL,
	`ES_STVL` INT(11) NULL DEFAULT NULL,
	`ES_HIVL` INT(11) NULL DEFAULT NULL,
	`ES_LOVL` INT(11) NULL DEFAULT NULL,
	`ES_TRS` INT(11) NULL DEFAULT NULL,
	`rrsidno` VARCHAR(40) NULL DEFAULT NULL,
	`rrt` DATE NULL DEFAULT NULL,
	`modidno` VARCHAR(40) NULL DEFAULT NULL,
	`modrrt` DATE NULL DEFAULT NULL,
	UNIQUE INDEX `CO_CD_ES_DT_ES_TIME` (`CO_CD`, `ES_DT`, `ES_TIME`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
