CREATE TABLE `sys_req_mt` (
	`seq` INT(11) NOT NULL AUTO_INCREMENT,
	`req_nm` VARCHAR(20) NOT NULL,
	`req_mth` VARCHAR(20) NULL DEFAULT NULL,
	`req_acc` VARCHAR(100) NULL DEFAULT NULL,
	`req_acen` VARCHAR(50) NULL DEFAULT NULL,
	`req_aclg` VARCHAR(50) NULL DEFAULT NULL,
	`req_cach` VARCHAR(20) NULL DEFAULT NULL,
	`req_con` VARCHAR(20) NULL DEFAULT NULL,
	`req_dnt` VARCHAR(4) NULL DEFAULT NULL,
	`req_ck` VARCHAR(2000) NULL DEFAULT NULL,
	`req_host` VARCHAR(50) NULL DEFAULT NULL,
	`req_ref` VARCHAR(500) NULL DEFAULT NULL,
	`req_uir` VARCHAR(4) NULL DEFAULT NULL,
	`req_agent` VARCHAR(200) NULL DEFAULT NULL,
	`rrsidno` VARCHAR(30) NULL DEFAULT 'SYSTEM',
	`rrt` DATETIME NULL DEFAULT NULL,
	`useyn` VARCHAR(4) NOT NULL DEFAULT 'Y',
	PRIMARY KEY (`seq`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=4
;
