CREATE TABLE `sys_usr_mt` (
	`usr_no` VARCHAR(40) NULL DEFAULT NULL,
	`usr_email` VARCHAR(100) NULL DEFAULT NULL,
	`usr_nm` VARCHAR(100) NULL DEFAULT NULL,
	`usr_pw` VARCHAR(2000) NULL DEFAULT NULL,
	`usr_pwq` VARCHAR(100) NULL DEFAULT NULL,
	`usr_pwa` VARCHAR(100) NULL DEFAULT NULL,
	`usr_use_yn` VARCHAR(2) NULL DEFAULT NULL,
	`rrsidno` VARCHAR(40) NULL DEFAULT NULL,
	`rrt` DATE NULL DEFAULT NULL,
	`modidno` VARCHAR(40) NULL DEFAULT NULL,
	`modrrt` DATE NULL DEFAULT NULL
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
