CREATE TABLE `sys_meta_mt` (
	`SCR_SITE_NM` VARCHAR(100) NULL DEFAULT NULL,
	`SCR_URL_PATH` VARCHAR(500) NULL DEFAULT NULL,
	`SCR_TP_TM` VARCHAR(8) NULL DEFAULT NULL,
	`SCR_TP_CD` VARCHAR(8) NULL DEFAULT NULL,
	`SCR_RULE_NO` VARCHAR(40) NULL DEFAULT NULL,
	`SCR_AVG_EXT` INT(11) NULL DEFAULT NULL,
	`SCR_RCT_EXT` INT(11) NULL DEFAULT NULL,
	`SCR_USE_YN` VARCHAR(2) NULL DEFAULT NULL,
	`rrsidno` VARCHAR(40) NULL DEFAULT NULL,
	`rrt` DATE NULL DEFAULT NULL,
	`modidno` VARCHAR(40) NULL DEFAULT NULL,
	`modrrt` DATE NULL DEFAULT NULL
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
