CREATE TABLE `sys_scrl_mt` (
	`SCR_RULE_NO` VARCHAR(40) NULL DEFAULT NULL,
	`SCR_RULE_GEN` VARCHAR(8) NULL DEFAULT NULL,
	`SCR_RULE_KEYV` VARCHAR(40) NULL DEFAULT NULL,
	`SCR_RULE_STAV` VARCHAR(8) NULL DEFAULT NULL,
	`SCR_RULE_ENDV` VARCHAR(8) NULL DEFAULT NULL,
	`SCR_USE_YN` VARCHAR(2) NULL DEFAULT NULL,
	`rrsidno` VARCHAR(40) NULL DEFAULT NULL,
	`rrt` DATE NULL DEFAULT NULL,
	`modidno` VARCHAR(40) NULL DEFAULT NULL,
	`modrrt` DATE NULL DEFAULT NULL
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
