CREATE TABLE `stk_noti_mt` (
	`NTC_CD` VARCHAR(40) NULL DEFAULT NULL,
	`ES_DT` VARCHAR(8) NULL DEFAULT NULL,
	`CO_CD` VARCHAR(40) NULL DEFAULT NULL,
	`NTC_NM` VARCHAR(200) NULL DEFAULT NULL,
	`NTC_DET` VARCHAR(2000) NULL DEFAULT NULL,
	`rrsidno` VARCHAR(40) NULL DEFAULT NULL,
	`rrt` DATE NULL DEFAULT NULL,
	`modidno` VARCHAR(40) NULL DEFAULT NULL,
	`modrrt` DATE NULL DEFAULT NULL
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
