CREATE TABLE `stk_inv_mt` (
	`CO_CD` VARCHAR(40) NULL DEFAULT NULL,
	`ES_DT` VARCHAR(8) NULL DEFAULT NULL,
	`INS_NET_BUY` INT(11) NULL DEFAULT NULL,
	`OVR_NET_BUY` INT(11) NULL DEFAULT NULL,
	`OVR_STH_AMT` INT(11) NULL DEFAULT NULL,
	`OVR_STH_RAT` INT(11) NULL DEFAULT NULL,
	`rrsidno` VARCHAR(40) NULL DEFAULT NULL,
	`rrt` DATE NULL DEFAULT NULL,
	`modidno` VARCHAR(40) NULL DEFAULT NULL,
	`modrrt` DATE NULL DEFAULT NULL
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
